// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYWubSxnGllcoSdzH74e7MrhTQcCmlD6k',
    appId: '1:441477963781:web:7e55bbdb5054d53106fc6c',
    messagingSenderId: '441477963781',
    projectId: 'speedtalks-732f2',
    authDomain: 'speedtalks-732f2.firebaseapp.com',
    storageBucket: 'speedtalks-732f2.firebasestorage.app',
    measurementId: 'G-DF7X3YTE7J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVqWt83hXDJr7oIi9D1ELm9GUcJBHE4zM',
    appId: '1:441477963781:android:3137024b4065e61306fc6c',
    messagingSenderId: '441477963781',
    projectId: 'speedtalks-732f2',
    storageBucket: 'speedtalks-732f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_-wxOi3wtSa8Fad18t9rgAgUIskChm1I',
    appId: '1:441477963781:ios:b27f73d079154ae906fc6c',
    messagingSenderId: '441477963781',
    projectId: 'speedtalks-732f2',
    storageBucket: 'speedtalks-732f2.firebasestorage.app',
    iosClientId: '441477963781-16lnbig19gm93hvekv3coruda4sh1tm0.apps.googleusercontent.com',
    iosBundleId: 'com.speedtalks.speedtalks',
  );
}
